import PDFDocument from 'pdfkit';

/**
 * Sanitizes a filename for use in HTTP Content-Disposition headers.
 * Strips special characters, controls chars, and quotes to prevent header injection.
 */
export const sanitizeFilename = (name, fallback = 'export') => {
  if (!name || typeof name !== 'string') return fallback;
  const sanitized = name
    .replace(/[<>:"/\\|?*\x00-\x1F\x7F#%&{}\\$!'`=@+]/g, '')
    .trim()
    .replace(/\s+/g, '_')
    .replace(/_{2,}/g, '_')
    .slice(0, 80);
  return sanitized || fallback;
};

/**
 * Generates plain text export for a Note including all full sections and subsections.
 */
export const generateNoteTxt = (note) => {
  const title = note.title || note.topic || 'Untitled Study Note';
  const topic = note.topic || 'General';
  const difficulty = note.difficulty || 'HERO';
  const subject = note.subject || '';
  const dateStr = note.createdAt ? new Date(note.createdAt).toLocaleDateString() : 'N/A';
  const summary = note.summary || 'No summary available.';

  const lines = [
    '================================================================================',
    'STUDYVERSE // KNOWLEDGE LAB STUDY DOSSIER',
    '================================================================================',
    `TITLE:      ${title}`,
    `TOPIC:      ${topic}`,
    `TIER:       ${difficulty}`,
    ...(subject ? [`SUBJECT:    ${subject}`] : []),
    `DATE:       ${dateStr}`,
    '--------------------------------------------------------------------------------',
    '',
    '[OVERVIEW & CORE CONCEPT]',
    summary,
    ''
  ];

  // Full Sections
  if (Array.isArray(note.sections) && note.sections.length > 0) {
    lines.push('[CORE DOSSIER SECTIONS]');
    note.sections.forEach((sec, idx) => {
      lines.push(`${idx + 1}. ${sec.title || `Section ${idx + 1}`}`);
      lines.push(sec.content || '');
      lines.push('');
    });
  }

  // Worked Examples & Case Studies
  if (Array.isArray(note.examples) && note.examples.length > 0) {
    lines.push('[WORKED EXAMPLES & CASE STUDIES]');
    note.examples.forEach((ex, idx) => {
      lines.push(`${idx + 1}. ${ex.title || 'Example'}:`);
      lines.push(`   ${ex.content || ''}`);
      lines.push('');
    });
  }

  // Key Mastery Points
  if (Array.isArray(note.bulletPoints) && note.bulletPoints.length > 0) {
    lines.push('[KEY MASTERY POINTS]');
    note.bulletPoints.forEach((pt, i) => {
      lines.push(`  • ${pt}`);
    });
    lines.push('');
  }

  // Common Traps & Misconceptions
  if (Array.isArray(note.commonMistakes) && note.commonMistakes.length > 0) {
    lines.push('[COMMON TRAPS & MISCONCEPTIONS]');
    note.commonMistakes.forEach((m) => {
      lines.push(`  ! ${m}`);
    });
    lines.push('');
  }

  // Exam Strategy & High-Yield Tips
  if (Array.isArray(note.examTips) && note.examTips.length > 0) {
    lines.push('[EXAM STRATEGY & HIGH-YIELD TIPS]');
    note.examTips.forEach((tip) => {
      lines.push(`  * ${tip}`);
    });
    lines.push('');
  }

  // Key Facts
  if (Array.isArray(note.keyFacts) && note.keyFacts.length > 0) {
    lines.push('[HIGH-YIELD REVISION TAKEAWAYS]');
    note.keyFacts.forEach((fact) => {
      lines.push(`  + ${fact}`);
    });
    lines.push('');
  }

  // S.A.T.U.R.D.A.Y. Exam Alert
  if (note.examAlert) {
    lines.push('[S.A.T.U.R.D.A.Y. EXAM ALERT / TRAPS]');
    lines.push(note.examAlert);
    lines.push('');
  }

  lines.push('================================================================================');
  lines.push('Generated by StudyVerse AI Study Assistant');

  return lines.join('\n');
};

/**
 * Streams a full-content multi-page PDF export for a Note into the Express response stream.
 * Renders all sections, examples, misconceptions, exam tips, bullet points, and exam alerts
 * using PDFKit's natural text flow without manual page breaks or trailing blank pages.
 */
export const streamNotePdf = (note, res) => {
  const doc = new PDFDocument({
    margins: { top: 45, bottom: 45, left: 45, right: 45 },
    size: 'A4',
    bufferPages: true
  });
  doc.pipe(res);

  const title = note.title || note.topic || 'Untitled Study Note';
  const topic = note.topic || 'General Concept';
  const difficulty = note.difficulty || 'HERO';
  const subject = note.subject || '';
  const dateStr = note.createdAt ? new Date(note.createdAt).toLocaleDateString() : new Date().toLocaleDateString();

  const contentWidth = 595.28 - 45 - 45; // 505.28 pt

  // Header Banner
  doc
    .fontSize(9.5)
    .font('Helvetica-Bold')
    .fillColor('#0284c7')
    .text('STUDYVERSE // KNOWLEDGE LAB DOSSIER', { tracking: 1.5 });

  doc.moveDown(0.25);

  // Title
  doc
    .fontSize(16)
    .font('Helvetica-Bold')
    .fillColor('#0f172a')
    .text(title, { lineGap: 1.5 });

  doc.moveDown(0.25);

  // Metadata Bar
  const subjectPart = subject ? `   |   SUBJECT: ${subject.toUpperCase()}` : '';
  doc
    .fontSize(8.5)
    .font('Helvetica')
    .fillColor('#64748b')
    .text(`TOPIC: ${topic.toUpperCase()}   |   TIER: ${difficulty}${subjectPart}   |   DATE: ${dateStr}`);

  doc.moveDown(0.35);

  // Top Rule
  doc
    .strokeColor('#cbd5e1')
    .lineWidth(1)
    .moveTo(45, doc.y)
    .lineTo(45 + contentWidth, doc.y)
    .stroke();

  doc.moveDown(0.5);

  let sectionCounter = 1;

  // 1. Overview / Summary Section
  if (note.summary || note.overview) {
    doc
      .fontSize(10.5)
      .font('Helvetica-Bold')
      .fillColor('#0284c7')
      .text(`${sectionCounter++}. OVERVIEW & CORE CONCEPT`);

    doc.moveDown(0.2);

    doc
      .fontSize(9)
      .font('Helvetica')
      .fillColor('#334155')
      .lineGap(2)
      .text(note.summary || note.overview || '');

    doc.moveDown(0.5);
  }

  // 2. Full Structured Sections
  if (Array.isArray(note.sections) && note.sections.length > 0) {
    note.sections.forEach((section) => {
      if (!section || (!section.title && !section.content)) return;
      const secTitle = section.title || `Section ${sectionCounter}`;
      doc
        .fontSize(10.5)
        .font('Helvetica-Bold')
        .fillColor('#0f172a')
        .text(`${sectionCounter++}. ${secTitle.toUpperCase()}`);

      doc.moveDown(0.2);

      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#334155')
        .lineGap(2)
        .text(section.content || '');

      doc.moveDown(0.5);
    });
  }

  // 3. Worked Examples & Case Studies
  if (Array.isArray(note.examples) && note.examples.length > 0) {
    const validExamples = note.examples.filter((ex) => ex && (ex.title || ex.content));
    if (validExamples.length > 0) {
      doc
        .fontSize(10.5)
        .font('Helvetica-Bold')
        .fillColor('#1d4ed8')
        .text(`${sectionCounter++}. WORKED EXAMPLES & CASE STUDIES`);

      doc.moveDown(0.2);

      validExamples.forEach((ex, idx) => {
        doc
          .fontSize(9.5)
          .font('Helvetica-Bold')
          .fillColor('#1e40af')
          .text(`Case ${idx + 1}: ${ex.title || 'Example'}`, { lineGap: 1.5 });

        doc.moveDown(0.15);

        doc
          .fontSize(9)
          .font('Helvetica')
          .fillColor('#334155')
          .lineGap(2)
          .text(ex.content || '');

        doc.moveDown(0.35);
      });

      doc.moveDown(0.2);
    }
  }

  // 4. Key Mastery Points
  if (Array.isArray(note.bulletPoints) && note.bulletPoints.length > 0) {
    const validBullets = note.bulletPoints.filter((b) => b && typeof b === 'string' && b.trim().length > 0);
    if (validBullets.length > 0) {
      doc
        .fontSize(10.5)
        .font('Helvetica-Bold')
        .fillColor('#0284c7')
        .text(`${sectionCounter++}. KEY MASTERY POINTS`);

      doc.moveDown(0.2);

      validBullets.forEach((pt) => {
        doc
          .fontSize(9)
          .font('Helvetica-Bold')
          .fillColor('#d97706')
          .text('• ', { continued: true })
          .font('Helvetica')
          .fillColor('#334155')
          .text(pt, { lineGap: 2 });
        doc.moveDown(0.12);
      });

      doc.moveDown(0.4);
    }
  }

  // 5. Common Traps & Misconceptions
  if (Array.isArray(note.commonMistakes) && note.commonMistakes.length > 0) {
    const validMistakes = note.commonMistakes.filter((m) => m && typeof m === 'string' && m.trim().length > 0);
    if (validMistakes.length > 0) {
      doc
        .fontSize(10.5)
        .font('Helvetica-Bold')
        .fillColor('#be123c')
        .text(`${sectionCounter++}. COMMON TRAPS & MISCONCEPTIONS`);

      doc.moveDown(0.2);

      validMistakes.forEach((m) => {
        doc
          .fontSize(9)
          .font('Helvetica-Bold')
          .fillColor('#e11d48')
          .text('! ', { continued: true })
          .font('Helvetica')
          .fillColor('#334155')
          .text(m, { lineGap: 2 });
        doc.moveDown(0.12);
      });

      doc.moveDown(0.4);
    }
  }

  // 6. Exam Strategy & High-Yield Tips
  if (Array.isArray(note.examTips) && note.examTips.length > 0) {
    const validTips = note.examTips.filter((t) => t && typeof t === 'string' && t.trim().length > 0);
    if (validTips.length > 0) {
      doc
        .fontSize(10.5)
        .font('Helvetica-Bold')
        .fillColor('#b45309')
        .text(`${sectionCounter++}. EXAM STRATEGY & HIGH-YIELD TIPS`);

      doc.moveDown(0.2);

      validTips.forEach((tip) => {
        doc
          .fontSize(9)
          .font('Helvetica-Bold')
          .fillColor('#d97706')
          .text('* ', { continued: true })
          .font('Helvetica')
          .fillColor('#334155')
          .text(tip, { lineGap: 2 });
        doc.moveDown(0.12);
      });

      doc.moveDown(0.4);
    }
  }

  // 7. Key Facts
  if (Array.isArray(note.keyFacts) && note.keyFacts.length > 0) {
    const validFacts = note.keyFacts.filter((f) => f && typeof f === 'string' && f.trim().length > 0);
    if (validFacts.length > 0) {
      doc
        .fontSize(10.5)
        .font('Helvetica-Bold')
        .fillColor('#0284c7')
        .text(`${sectionCounter++}. HIGH-YIELD REVISION TAKEAWAYS`);

      doc.moveDown(0.2);

      validFacts.forEach((fact) => {
        doc
          .fontSize(9)
          .font('Helvetica-Bold')
          .fillColor('#0284c7')
          .text('+ ', { continued: true })
          .font('Helvetica')
          .fillColor('#334155')
          .text(fact, { lineGap: 2 });
        doc.moveDown(0.12);
      });

      doc.moveDown(0.4);
    }
  }

  // 8. Exam Alert Callout
  if (note.examAlert && typeof note.examAlert === 'string' && note.examAlert.trim().length > 0) {
    doc
      .fontSize(10.5)
      .font('Helvetica-Bold')
      .fillColor('#b45309')
      .text('! S.A.T.U.R.D.A.Y. EXAM ALERT');

    doc.moveDown(0.2);

    doc
      .fontSize(9)
      .font('Helvetica')
      .fillColor('#78350f')
      .lineGap(2)
      .text(note.examAlert);
  }

  // Multi-page Footers: reset bottom margin temporarily so footer text never triggers an auto-page-add
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const origBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    doc
      .fontSize(8)
      .font('Helvetica')
      .fillColor('#94a3b8')
      .text(
        `StudyVerse Knowledge Lab • Academic Dossier • Page ${i + 1} of ${range.count}`,
        45,
        805,
        { align: 'center', width: contentWidth, lineBreak: false }
      );
    doc.page.margins.bottom = origBottom;
  }

  doc.end();
};

/**
 * Generates plain JSON export for a Quiz.
 */
export const generateQuizJson = (quiz) => {
  const quizObj = quiz.toObject ? quiz.toObject() : quiz;
  return {
    id: quizObj._id ? quizObj._id.toString() : quizObj.id,
    topic: quizObj.topic,
    difficulty: quizObj.difficulty || 'HERO',
    submitted: !!quizObj.submitted,
    score: quizObj.score || 0,
    totalQuestions: quizObj.questions?.length || 0,
    questions: (quizObj.questions || []).map((q, idx) => ({
      id: q.id || `q${idx + 1}`,
      question: q.question,
      options: q.options || [],
      correctAnswer: q.correctAnswer,
      correctOptionText:
        Array.isArray(q.options) && typeof q.correctAnswer === 'number'
          ? q.options[q.correctAnswer]
          : null,
      explanation: q.explanation || '',
      xp: q.xp || 50
    })),
    createdAt: quizObj.createdAt || new Date().toISOString(),
    exportedAt: new Date().toISOString()
  };
};

/**
 * Streams a PDF export for a Quiz into the Express response stream.
 */
export const streamQuizPdf = (quiz, res) => {
  const doc = new PDFDocument({
    margins: { top: 45, bottom: 45, left: 45, right: 45 },
    size: 'A4',
    bufferPages: true
  });
  doc.pipe(res);

  const quizObj = quiz.toObject ? quiz.toObject() : quiz;
  const topic = quizObj.topic || 'Battle Arena Combat Quiz';
  const difficulty = quizObj.difficulty || 'HERO';
  const questions = quizObj.questions || [];
  const dateStr = quizObj.createdAt ? new Date(quizObj.createdAt).toLocaleDateString() : new Date().toLocaleDateString();

  const contentWidth = 595.28 - 45 - 45; // 505.28 pt

  // Header Banner
  doc
    .fontSize(9.5)
    .font('Helvetica-Bold')
    .fillColor('#dc2626')
    .text('STUDYVERSE // BATTLE ARENA COMBAT DOSSIER', { tracking: 1.5 });

  doc.moveDown(0.25);

  // Title
  doc
    .fontSize(16)
    .font('Helvetica-Bold')
    .fillColor('#0f172a')
    .text(topic);

  doc.moveDown(0.25);

  // Metadata
  const scoreInfo = quizObj.submitted
    ? `   |   SCORE: ${quizObj.score}/${questions.length} (${Math.round((quizObj.score / (questions.length || 1)) * 100)}%)`
    : '';

  doc
    .fontSize(8.5)
    .font('Helvetica')
    .fillColor('#64748b')
    .text(`TIER: ${difficulty}   |   QUESTIONS: ${questions.length}   |   DATE: ${dateStr}${scoreInfo}`);

  doc.moveDown(0.35);

  // Top Rule
  doc
    .strokeColor('#cbd5e1')
    .lineWidth(1)
    .moveTo(45, doc.y)
    .lineTo(45 + contentWidth, doc.y)
    .stroke();

  doc.moveDown(0.6);

  // Questions List
  questions.forEach((q, idx) => {
    // Question Number and Title
    doc
      .fontSize(10.5)
      .font('Helvetica-Bold')
      .fillColor('#0f172a')
      .text(`Q${idx + 1}. ${q.question || 'Question'}`, { lineGap: 1.5 });

    doc.moveDown(0.2);

    const optionLabels = ['A', 'B', 'C', 'D'];
    const options = Array.isArray(q.options) ? q.options : [];
    let correctIdx = q.correctAnswer;
    if (typeof correctIdx === 'string') {
      const parsed = parseInt(correctIdx, 10);
      correctIdx = isNaN(parsed) ? 0 : parsed;
    }

    options.forEach((opt, optIdx) => {
      const label = optionLabels[optIdx] || `${optIdx + 1}`;
      const isCorrect = optIdx === correctIdx;

      if (isCorrect) {
        doc
          .fontSize(9.5)
          .font('Helvetica-Bold')
          .fillColor('#15803d')
          .text(`    [${label}]  ${opt}   [CORRECT ANSWER]`, { lineGap: 1.2 });
      } else {
        doc
          .fontSize(9.5)
          .font('Helvetica')
          .fillColor('#475569')
          .text(`    [${label}]  ${opt}`, { lineGap: 1.2 });
      }
    });

    // Explanation
    if (q.explanation) {
      doc.moveDown(0.15);
      doc
        .fontSize(8.5)
        .font('Helvetica-Oblique')
        .fillColor('#64748b')
        .text(`    Intel Explanation: ${q.explanation}`, { lineGap: 1.5 });
    }

    doc.moveDown(0.5);
  });

  // Footer: reset bottom margin temporarily so footer text never triggers an auto-page-add
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const origBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    doc
      .fontSize(8)
      .font('Helvetica')
      .fillColor('#94a3b8')
      .text(
        `StudyVerse Superhero Battle Arena • Combat Intel Dossier • Page ${i + 1} of ${range.count}`,
        45,
        805,
        { align: 'center', width: contentWidth, lineBreak: false }
      );
    doc.page.margins.bottom = origBottom;
  }

  doc.end();
};
