import api from './api';
import { userGet, userSet } from '../utils/userStorage';
import { downloadApiFile, downloadClientFile } from '../utils/download';

const NOTES_KEY = 'studyverse_vault_notes';

export const notesService = {
  getNotes: async () => {
    try {
      const response = await api.get('/notes');
      userSet(NOTES_KEY, response.data); // per-user offline cache
      return response.data;
    } catch {
      // Offline: this user's own cached notes — an empty array for a
      // brand-new user (never another user's or mock data).
      const stored = userGet(NOTES_KEY);
      return stored ? JSON.parse(stored) : [];
    }
  },

  saveNote: async (note) => {
    const localNote = {
      ...note,
      id: `note-${Date.now()}`,
      createdDate: 'Just now',
      createdAt: new Date().toISOString()
    };
    try {
      const res = await api.post('/notes', note);
      return res.data;
    } catch {
      const existing = await notesService.getNotes();
      const updated = [localNote, ...existing];
      userSet(NOTES_KEY, updated);
      return localNote;
    }
  },

  deleteNote: async (id) => {
    try {
      await api.delete(`/notes/${id}`);
    } catch {
      const existing = await notesService.getNotes();
      userSet(
        NOTES_KEY,
        existing.filter((n) => n.id !== id)
      );
    }
  },

  exportNote: async (id, format = 'pdf', noteData = null) => {
    const cleanTitle = (noteData?.title || noteData?.topic || 'study_note').replace(/[^a-zA-Z0-9_-]/g, '_');
    const fallbackFilename = `${cleanTitle}.${format}`;

    try {
      if (id && !String(id).startsWith('note-')) {
        return await downloadApiFile(`/notes/${id}/export?format=${format}`, fallbackFilename);
      }
    } catch (err) {
      console.warn('[notesService] Backend export failed, checking offline fallback:', err);
    }

    // Offline fallback for plain text if backend note not available
    if (format === 'txt' && noteData) {
      const lines = [
        '================================================================================',
        'STUDYVERSE // KNOWLEDGE LAB STUDY DOSSIER',
        '================================================================================',
        `TITLE:      ${noteData.title || noteData.topic || 'Untitled'}`,
        `TOPIC:      ${noteData.topic || 'General'}`,
        `TIER:       ${noteData.difficulty || 'HERO'}`,
        ...(noteData.subject ? [`SUBJECT:    ${noteData.subject}`] : []),
        '--------------------------------------------------------------------------------',
        '',
        '[OVERVIEW & CORE CONCEPT]',
        noteData.summary || noteData.overview || 'No summary available.',
        ''
      ];

      // Full Sections
      if (Array.isArray(noteData.sections) && noteData.sections.length > 0) {
        lines.push('[CORE DOSSIER SECTIONS]');
        noteData.sections.forEach((sec, idx) => {
          lines.push(`${idx + 1}. ${sec.title || `Section ${idx + 1}`}`);
          lines.push(sec.content || '');
          lines.push('');
        });
      }

      // Worked Examples
      if (Array.isArray(noteData.examples) && noteData.examples.length > 0) {
        lines.push('[WORKED EXAMPLES & CASE STUDIES]');
        noteData.examples.forEach((ex, idx) => {
          lines.push(`${idx + 1}. ${ex.title || 'Example'}:`);
          lines.push(`   ${ex.content || ''}`);
          lines.push('');
        });
      }

      // Key Mastery Points
      if (Array.isArray(noteData.bulletPoints) && noteData.bulletPoints.length > 0) {
        lines.push('[KEY MASTERY POINTS]');
        noteData.bulletPoints.forEach((b) => lines.push(`  • ${b}`));
        lines.push('');
      }

      // Common Traps & Misconceptions
      if (Array.isArray(noteData.commonMistakes) && noteData.commonMistakes.length > 0) {
        lines.push('[COMMON TRAPS & MISCONCEPTIONS]');
        noteData.commonMistakes.forEach((m) => lines.push(`  ! ${m}`));
        lines.push('');
      }

      // Exam Strategy & High-Yield Tips
      if (Array.isArray(noteData.examTips) && noteData.examTips.length > 0) {
        lines.push('[EXAM STRATEGY & HIGH-YIELD TIPS]');
        noteData.examTips.forEach((tip) => lines.push(`  * ${tip}`));
        lines.push('');
      }

      // High-Yield Revision Takeaways
      if (Array.isArray(noteData.keyFacts) && noteData.keyFacts.length > 0) {
        lines.push('[HIGH-YIELD REVISION TAKEAWAYS]');
        noteData.keyFacts.forEach((fact) => lines.push(`  + ${fact}`));
        lines.push('');
      }

      // S.A.T.U.R.D.A.Y. Exam Alert
      if (noteData.examAlert) {
        lines.push('[S.A.T.U.R.D.A.Y. EXAM ALERT / TRAPS]');
        lines.push(noteData.examAlert);
        lines.push('');
      }

      lines.push('================================================================================');
      lines.push('Generated by StudyVerse AI Study Assistant');

      downloadClientFile(lines.join('\n'), fallbackFilename, 'text/plain;charset=utf-8');
      return fallbackFilename;
    }

    // If PDF and offline without backend, retry API
    return await downloadApiFile(`/notes/${id}/export?format=${format}`, fallbackFilename);
  }
};

